#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username : root
#    password : root123456
#    driver-class-name: com.mysql.jdbc.Driver
#  activiti:
#    database-schema-update: true
#    db-history-used: true
#    history-level: full
#    check-process-definitions: false
#    async-executor-activate: true
